spring:
  application:
    name: log-analyzer
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/log_analyzer}
    username: ${DB_USERNAME:log_analyzer}
    password: ${DB_PASSWORD:local_dev_password}
    hikari:
      connection-timeout: 2000
      validation-timeout: 1000
      data-source-properties:
        connectTimeout: 2
        socketTimeout: 3
  jdbc:
    template:
      query-timeout: 2s
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
server:
  port: 8080
  error:
    include-message: never
    include-stacktrace: never