spring:
  application:
    name: log-analyzer
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/log_analyzer}
    username: ${DB_USERNAME:log_analyzer}
    password: ${DB_PASSWORD:local_dev_password}
    hikari:
      connection-timeout: 2000
      validation-timeout: 1000
      data-source-properties:
        connectTimeout: 2
        socketTimeout: 3
  jdbc:
    template:
      query-timeout: 2s
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      connect-timeout: 2s
      timeout: 2s
      repositories:
        enabled: false
  cache:
    type: redis
    cache-names: log-overview
    redis:
      time-to-live: 45s
      enable-statistics: true
      key-prefix: "log-analyzer:"
server:
  port: 8080
  error:
    include-message: never
    include-stacktrace: never
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus